### ISSUE TITLE
Imperative expectations

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mulang#11]
We need more expectations and support for imperative languages. 
- `usesSwitch`
- `usesFor`
- `declaresProcedure`
- `declaresRecord` 

@faloi please suggest here what you need for Gobstones

**Comment by faloi** [comment]
Right now, I can think of these:

* `usesRepeat`
* `usesWhile`
* `usesForeach`
* `declaresFunction` - we should think about this, because for every other language this is the same as `declaresProcedure`
* `declaresVariable`

**Comment by trimegisto87** [comment]
The following expectations are already :

- declaresFunction
- usesWhile
- usesIf
- usesRepeat

**Comment by flbulgarelli** [comment]
Solved, as previous comment
