### ISSUE TITLE
Expectativas Uses: y Calls: fallan cuando el método se utiliza para asignar a un atributo en Ruby

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mulang#129]
Para las expectativas:
`gastar_energia! Calls: distancia_a`
y 
`gastar_energia! Uses: distancia_a`

Y el código
```
  def self.gastar_energia!(destino)
    @energia = @energia - self.distancia_a(destino) / 2
  end
```

No se cumple el objetivo **gastar_energia! debe utilizar distancia_a**

Cambiando el código de modo que no asigne a un atributo, la expectativa se cumple. Por ejemplo:
```
  def self.gastar_energia!(destino)
    @energia + self.distancia_a(destino) / 2
  end
```

Entiendo que Calls: y Uses: son indistintos en este caso.

Quizá en todos los lugares donde dice expectativa quise decir inspección, pero tampoco estoy seguro 
![](http://i0.kym-cdn.com/photos/images/original/001/038/787/4d4.jpg)

**Comment by flbulgarelli** [comment]
> Entiendo que Calls: y Uses: son indistintos en este caso.

Correcto. Uses es una inspección general, "usa" en sentido amplio, que valida que haya alguna referencia. Calls es un caso particular que sólo funciona para llamadas/aplicaciones/envíos de mensajes. 

> Cambiando el código de modo que no asigne a un atributo, la expectativa se cumple. 

Si, definitivamente es un bug.
