### ISSUE TITLE
Generated mulang AST can be ambiguous

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mulang#134]
There are cases where a possibly non-existing field is being represented as a MuNull, but this causes ambiguousness.

An example of this is the return expression, which has the type Return Expression.

If nothing is being returned this would be parsed as Return MuNull, but this could also mean that the user is actively returning null.

Possible solutions would include using Maybe monads on places where something might not exist or introducing a new data type which encompasses this possibility.

**Comment by flbulgarelli** [comment]
Some examples:

```javascript
var a;
var a = null;
var a = undefined;
```

All map to:

```
Variable 'a' MuNull
```


If we had a `assignsNull`, it would incorrectly report the first and last cases. 


This also happens with: ifs, attribute and return declaration - actually `returnsNull` is buggy when someone writes `return` in C-like languages.

**Comment by flbulgarelli** [comment]
I propose introducing a new `MuNil` constructor, that maps to `null/nil` in reference-based languages, and keep `MuNull` with an `undefined`/empty block semantics.
