### ISSUE TITLE
No funciona la inspección de detectar variables en gobstones

### ISSUE THREAD

**Issue by aguspina** [mumuki/mulang#153]
<img width="1440" alt="screen shot 2018-04-09 at 16 13 33" src="https://user-images.githubusercontent.com/4105740/38517632-f912e6d6-3c10-11e8-9b05-6389eac9fd44.png">

**Comment by flbulgarelli** [comment]
Gobstones does no support `DeclaresVariable` by design, because there is no such thing as variable declaration in gobstones. You must use `AssignsVariable`. Please fix the content.
