### ISSUE TITLE
Add support for case insensitive matching

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mulang#155]
As part of the GobstonesJr support, we need to be able to accept and be able to match computation names that are both case insensitive and space insensitive. 

For example, the expectation `* Declares:Sembrar Tomate` should be true if `Sembrar Tomate`, `SembrarTomate`, `Sembrar     Tomate` or `sembrartomate` is declared.

**Comment by rodri042** [comment]
Pregunta: ¿El "space insensitive" por qué lo necesitamos?

Actualmente el componente de bloques saca todos los espacios de todos lados:
![screenshot4](https://user-images.githubusercontent.com/1631752/38829646-2a9cebc8-4190-11e8-95a8-7c4b7cb09a5b.png)

Y el AST de mulang ni se entera de que alguna vez el procedimiento se llamó "Sembrar Tomate", porque se arma a partir del código generado.

---

Sobre el case insensitive:
Gobstones diferencia funciones de procedimientos por su caracter inicial. Y permite tener variables con el mismo nombre que una función (porque las funciones solo se pueden usar invocándolas). Ejemplo:
```js
program {
    sembrarTomate := Rojo

    if (sembrarTomate()) {
        SembrarTomate(sembrarTomate)
    }
}

procedure SembrarTomate(sembrarTomate) {
    Poner(sembrarTomate)
}

function sembrarTomate() {
    return (True)
}
```
(y esto pone una bolita roja :P)

Y no es que cause problemas sino que con `Uses:sembrarTomate` no se va a saber si está usando la variable, llamando a la función o al procedimiento. Igual no estoy seguro de esto, tal vez `Uses:=` es para variables y `Uses:` solo para invocaciones pero seguro que no vamos a poder distinguir funciones de procedimientos.

**Comment by julian-berbel** [comment]
> Y no es que cause problemas sino que con Uses:sembrarTomate no se va a saber si está usando la variable, llamando a la función o al procedimiento. Igual no estoy seguro de esto, tal vez Uses:= es para variables y Uses: solo para invocaciones pero seguro que no vamos a poder distinguir funciones de procedimientos.

En realidad el ast diferencia entre procedimiento, función y variable con los nodos Procedure, Function y Variable, por lo que en ese sentido no habría problema.

Lo único que aportaría es que en el expectation el binding buscado no necesitaría seguir la convención de cases. ¯\_(ツ)_/¯

**Comment by julian-berbel** [comment]
Después de hablarlo con @flbulgarelli decidimos bajarle la prioridad pero dejarlo abierto por la posibilidad de en el futuro implementar el case insensitive-ness en los expectations

**Comment by flbulgarelli** [comment]
Closing. The like operator `~`  already address this since at least Mulang 5.
