### ISSUE TITLE
Create new expectation: Delegates

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mulang#194]
It's necessary an expectation to indicate that the user has delegated a few actions in a new procedure.  

For example: 

`program Delegates` == `program Uses:$a` + `* Declares:$a`

@flbulgarelli

**Comment by flbulgarelli** [comment]
Related to https://github.com/mumuki/mulang/issues/193

**Comment by flbulgarelli** [comment]
Fixed in https://github.com/mumuki/mulang/pull/212
