### ISSUE TITLE
Create Github page for this project

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mulang#196]
It would be nice to have a Github page that contains the README information using a more readable layout, and also a mulang online tester based on the .js distribution. It should: 

* Allow you to enter a Mulang AST and run inspections over it
* Allow you to transform one of the supported languages and transform it to mulang
* Run other analyses

**Comment by Javi** [comment]
I haven't yet made any Mumuki pages, are there any guidelines to follow? I also have little to no experience on mulang at all, so if there's any current usage of the .js dist to have as an example that would be useful to have as well

**Comment by flbulgarelli** [comment]
>I haven't yet made any Mumuki pages, are there any guidelines to follow? 

There are no documentation pages, yet. So you should start from scratch, but I can provide a few style guides. Also, you could use `mumuki-styles` dependency, in order to keep styles in sync. 

I am expecting something simple, that allows you to understand what mulang does, on the JS side, with an expressions parser - inspired on http://esprima.org/demo/parse.html - and that contains a few examples, copy pasted from the README.   

> I also have little to no experience on mulang at all, so if there's any current usage of the .js dist to have as an example that would be useful to have as well

Please have a look at the README. It has a few usage samples of both the cli tool and the JS library - which share the same JSON interface.
