### ISSUE TITLE
Update JS version usage information

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mulang#217]
We must update: 

- `npm install`  samples
- node usage samples as library code
- node usage samples as standalone program
- deployment instructions
- ghcjslib README

**Comment by flbulgarelli** [comment]
See https://github.com/mumuki/mulang/pull/207#issuecomment-452445193

**Comment by flbulgarelli** [comment]
PS: I am not being able to run `mulang-cli`

**Comment by julian-berbel** [comment]
> PS: I am not being able to run `mulang-cli`

aaaagggghhhhhhh. Apparently the package bin doesn't assume the given files are js files to be run with node, but rather it should take files that are directly executable by the os (we just need to add `#!/usr/bin/env node` at the beginning of the file) ((also, the require path is wrong, when deployed both mulang-cli and mulang are in the same folder, so it should not have `build/` in it))

**Comment by julian-berbel** [comment]
Maybe it would be better to keep the directory structure between the published package and development, since adding the aforementioned changes to the index.js file would then fix the published version, but break development
