### ISSUE TITLE
Uses: and NotUses: inspections with Math. methods don't work on JavaScript

### ISSUE THREAD

**Issue by felipecalvo** [mumuki/mulang#221]
Uses:/NotUses: Math.abs, Math.round and max (instead of Math.max, just to make sure) inspections are not working:

![screenshot_2019-01-14 mumuki - bibliotheca](https://user-images.githubusercontent.com/11304439/51122354-6bd59b00-17f8-11e9-91be-9440bd3ac6be.png)

Solution passes successfully even though it uses all three methods

![image](https://user-images.githubusercontent.com/11304439/51122407-90317780-17f8-11e9-86c6-50730e2ff0b6.png)

[Link to exercise](https://bibliotheca.mumuki.io/#/guides/flbulgarelli/fundamentos-javascript-funciones-tipos-de-datos/exercises/11)

**Comment by julian-berbel** [comment]
Not sure where exactly but this seems to have gotten fixed somewhere between mulang 4.3.0 and 4.4.0 already.

We only need to update and deploy the corresponding runner.

**Comment by felipecalvo** [comment]
It's still not working.

Here's a link to the exercise
https://mumuki.io/central/exercises/2771-programacion-imperativa-funciones-y-tipos-de-datos-y-que-tal-si

Solution sent in screenshot is
```
function maximo(uno, otro) {
  let a = Math.abs(uno);
  let b = Math.round(otro);
  return Math.max(uno, otro);
}

```

Current expectations are

> maximo Not:Uses: max
> maximo Not:Uses: Math.abs
> maximo Not:Uses: Math.round

**Comment by julian-berbel** [comment]
This is actually failing because the JS parser we're using does not support ECMAScript code, and therefore the `let`s are making the parser fail. Behavior seems fine using  `var`s. Apparently ECMAScript support has been recently added to our dependency, so we should try with updating the version we're using.
