### ISSUE TITLE
Expectation "Not:UsesForLoop"

### ISSUE THREAD

**Issue by Gustrucco** [mumuki/mulang#233]
In JavaScript there is no way to check if a `for` loop is used in a function. I tried using `Not:UsesForEach` and `Not:UsesLoop` and none of them worked.

Laboratory:
![image](https://user-images.githubusercontent.com/3957637/56218451-62e4a780-603b-11e9-9b57-ab4e1ba172e4.png)}

Bibliotheca:
![image](https://user-images.githubusercontent.com/3957637/56218613-ac34f700-603b-11e9-9b2b-d2bca6b51ba2.png)

**Comment by flbulgarelli** [comment]
This is actually not a problem of mulang itself nor the `UsesLoop` expectation. The problem is that this code is not being properly parsed by the javascript script parser. 

It looks like its current version does support `let`, but not `for...of`s.

**Comment by flbulgarelli** [comment]
On the meanwhile I have opened a PR here https://github.com/erikd/language-javascript/pull/84
