### ISSUE TITLE
HasUsage inspection fails when the function is part of a parameter of a higher order function 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mulang#32]
From issue https://github.com/mumuki/mumuki-atheneum/issues/514

Suppose the expectation for f is HasUsage:g, the following solutions for f pass the expectation

``` haskell
f list x = elem (g x) list
f list = flip elem list.g
f list x= any (\y -> y == g x) list
```

But these ones (and similar where g is applied as part of the parameter of a higher order function) do not, and end up stating g is not used:

``` haskell
f list x= any (== g x) list
f list x= ((>0).length.filter (== g x)) list
```

**Comment by julian-berbel** [comment]
Sounds like it could be related to #120. I’ll check if this is sill happening tomorrow.

**Comment by flbulgarelli** [comment]
@julian-berbel confirmed this is a duplicated of #120. Closing.
