### ISSUE TITLE
Instantiates expectation not properly working in java

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mulang#324]
In exercise https://mumuki.io/staging/exercises/3719-objetos-con-tipado-estatico-practica-colecciones-visitando-a-belgrano

The following solution:
```java
class LibroDeSugerencias {
  private List<String> sugerencias = new ArrayList();
  private Set<String> dnis = new TreeSet();

  void registrarSugerencia(String dni, String sugerencia) {
    sugerencias.add(sugerencia);
    dnis.add(dni);
  }

  List<String> sugerencias() {
    return sugerencias;
  }

  public int cantidadDnisUnicos() {
    return dnis.size();
  }
}
```

should pass with expectation `* Instantiates:HashSet` failing. However, the expectation does not seem to fail even when using TreeSet as in the given example.

**Comment by julian-berbel** [comment]
In a similar vein, the `* Users:HashMap` expectation in https://mumuki.io/staging/exercises/3743-objetos-con-tipado-estatico-practica-colecciones-contestador-automatico-recargado seems to be failing in a similar manner. Using `TreeMap` instead of HashMap does not raise a failed expectation.

**Comment by julian-berbel** [comment]
Additional insight: this problem seems to occur only with constants. While the expectation `* Uses:HashMap` does not work, the expectation `* Uses:getOrDefault` does.

**Comment by flbulgarelli** [comment]
I have just written this test and it pass :confused: 

```haskell
    it "is True when instantiates a HashSet" $ do
      instantiates (named "TreeSet") (java "class Main {  private Set<String> aSet = new TreeSet<>(); }") `shouldBe` True
      instantiates (named "HashSet") (java "class Main {  private Set<String> aSet = new TreeSet<>(); }") `shouldBe` False

    it "is False when not instantiates a HashSet" $ do
      instantiates (named "TreeSet") (java "class Main {  private Set<String> aSet = new HashSet<>(); }") `shouldBe` False
      instantiates (named "HashsSet") (java "class Main {  private Set<String> aSet = new HashSet<>(); }") `shouldBe` True
```

**Comment by flbulgarelli** [comment]
Even weirder: 

```ruby
# s is this issue's code
[29] pry(main)> Mulang::Code.native('Java', s).expect "*", "Instantiates:HaSSet"
=> false
[30] pry(main)> Mulang::Code.native('Java', s).expect "*", "Instantiates:HasSet"
```

**Comment by flbulgarelli** [comment]
Bingo!

```ruby
[39] pry(main)> Mulang::Expectation.parse(binding: "*", inspection: "Instantiates:TreeMap").as_v2
=> #<Mulang::Expectation::V2:0x00005557ca1eb7f8
 @binding="*",
 @inspection=
  #<Mulang::Inspection:0x00005557ca1eb870
   @i18n_namespace=nil,
   @matcher=nil,
   @negated=false,
   @target=#<Mulang::Inspection::Target:0x00005557ca1eba50 @type=:unknown, @value="TreeMap">,
   @type="Instantiates">>
[40] pry(main)> Mulang::Expectation.parse(binding: "*", inspection: "Instantiates:HashMap").as_v2
=> #<Mulang::Expectation::V2:0x00005557ca355be8
 @binding="*",
 @inspection=#<Mulang::Inspection:0x00005557ca355cd8 @i18n_namespace=nil, @matcher=nil, @negated=false, @target=nil, @type="Instantiates">>
[41] pry(main)> 
```

**Comment by julian-berbel** [comment]
Similarly to https://github.com/mumuki/mulang/issues/323, expectation detection is working properly, but the translation is off (not entirely missing this time) :thinking: 
![image](https://user-images.githubusercontent.com/11720274/106927724-36f35400-66f1-11eb-9f92-7906efb7f2d5.png)

First expectation is `* Instantiates:HashSet`
and second is `* Instantiates:Foobar`

Since only the first one is mistranslated it's probably related to the `Has` in the name again

**Comment by julian-berbel** [comment]
My bad, I just needed to update mulang in laboratory too!
