### ISSUE TITLE
TypesAttributeAs expectation not properly working

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mulang#327]
In exercise https://mumuki.io/staging/exercises/3720-objetos-con-tipado-estatico-practica-colecciones-permiso-yo-entre-primero

The following solution:
```java
class Panaderia {
  LinkedList<Cliente> cola = new LinkedList();
  
  public void entrar(Cliente unCliente){
    cola.offer(unCliente);
  }
  
  public LinkedList<Cliente> enEspera(){
    return cola;
  }
  
  public void atender(){
    cola.poll();
  }
  
}
```

Should pass with failed expectation `* TypesAttributeAs:Queue` but said expectation is not currently failing.

**Comment by flbulgarelli** [comment]
First insight: the `Type` is there, so there are no parsing issues

![image](https://user-images.githubusercontent.com/677436/106302013-2a758400-6237-11eb-993a-7dc65b412f6c.png)

**Comment by flbulgarelli** [comment]
Actually there is no issue :tada: Inspection `TypesAttributeAs` does not exist. It is not referenced in code nor in documentation. 

However there is a `TypesAs` inspection, which works as expected: 

```ruby
[53] pry(main)> Mulang::Code.native('Java', s).expect "*", "TypesAs:Queue"
=> false
[54] pry(main)> 
[55] pry(main)> Mulang::Code.native('Java', s).expect "*", "TypesAs:LinkedList"
=> true
```

So that looks just like a content error @Gustrucco

**Comment by julian-berbel** [comment]
Then I should add that this other exercise is using that expectation too: https://mumuki.io/staging/exercises/3802-objetos-con-tipado-estatico-colecciones-podes-cambiar-pero-no-redimensionarte

**Comment by flbulgarelli** [comment]
Duplicate of https://github.com/mumuki/mulang/issues/206
