### ISSUE TITLE
Newline after return is not considered in javascript

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mulang#338]
We had a student send the following solution:
```javascript
function promedioDeBalancesPositivos(balanceDeUnPeriodo){
  return //promedio(balanceDeUnPeriodo(gananciasDeBalancesPositivos))
  promedio(gananciasDeBalancesPositivos(balanceDeUnPeriodo))
}
```

The function body is being parsed as:
```haskell
Return (Application (Reference "promedio") [Application (Reference "gananciasDeBalancesPositivos" [Reference "balanceDeUnPeriodo"])])
```

When really the expected result should be something like:
```haskell
Sequence [
  Return None,
  Application (Reference "promedio") [Application (Reference "gananciasDeBalancesPositivos" [Reference "balanceDeUnPeriodo"])]
]
```

**Comment by julian-berbel** [comment]
So... upon closer inspection, this error really only occurs when that comment is there. A simple newline will be parsed properly, but it seems the comment being there is causing trouble.

It seems this bug comes from the [dependency we're using for parsing javascript](https://github.com/erikd/language-javascript). I fear we may have our hands tied here.

**Comment by flbulgarelli** [comment]
> It seems this bug comes from the dependency we're using for parsing javascript. I fear we may have our hands tied here.

There is a possible fix here https://github.com/mumuki/language-javascript/pull/1

It still needs some refactoring and testing, but I think it fixes the issue in a _right_ way
