### ISSUE TITLE
Error al crear listas infinitas

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mulang#42]
Ejercicio: La historia sin fin

Solución:

infinitosUnos = 1:infinitosUnos

u otra solución:

infinitosUnos = [1,1..]

Estado: errored

See http://algo2-undav.mumuki.io/guides/pdep-utn/mumuki-guia-funcional-recursividad 

Error completo:

Invalid JSON :
	A JSON text must at least contain two octets!:

-----
/var/lib/gems/2.0.0/gems/mumukit-core-0.1.3/lib/mumukit/core/json.rb:7:in `rescue in pretty_parse'
/var/lib/gems/2.0.0/gems/mumukit-core-0.1.3/lib/mumukit/core/json.rb:5:in `pretty_parse'
/var/lib/gems/2.0.0/gems/mumukit-2.5.0/lib/mumukit/templates/mulang_expectations_hook.rb:16:in `post_process_file'
/var/lib/gems/2.0.0/gems/mumukit-2.5.0/lib/mumukit/templates/file_hook.rb:11:in `run!'
/var/lib/gems/2.0.0/gems/mumukit-2.5.0/lib/mumukit/server/test_server.rb:86:in `compile_and_run'
/var/lib/gems/2.0.0/gems/mumukit-2.5.0/lib/mumukit/server/test_server.rb:72:in `run_expectations!'
/var/lib/gems/2.0.0/gems/mumukit-2.5.0/lib/mumukit/server/test_server.rb:36:in `block in test!'
/var/lib/gems/2.0.0/gems/mumukit-2.5.0/lib/mumukit/server/test_server.rb:111:in `respond_to'
/var/lib/gems/2.0.0/gems/mumukit-2.5.0/lib/mumukit/server/test_server.rb:34:in `test!'
/var/lib/gems/2.0.0/gems/mumukit-2.5.0/lib/mumukit/server/app.rb:51:in `block in <class:App>'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
/var/lib/gems/2.0.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
/var/lib/gems/2.0.0/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
/var/lib/gems/2.0.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:212:in `call'
/var/lib/gems/2.0.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
/var/lib/gems/2.0.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
/var/lib/gems/2.0.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
/var/lib/gems/2.0.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
/var/lib/gems/2.0.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
/var/lib/gems/2.0.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
/var/lib/gems/2.0.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
/var/lib/gems/2.0.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'

**Comment by flbulgarelli** [comment]
Hola!

No era un problema de las listas infinitas al final. Simplemente había un error de redacción en una de las expectativas (estaba vacía, lo cual en febrero el editor no validaba, pero ahora sí). Corregí el ejercicio y salió andando :)

**Comment by estefaniamiguel** [comment]
Ahhh las expectativas era? Yo me fijé solo en los test, no me acordaba que era obligatorio tener expectativas

**Comment by flbulgarelli** [comment]
No, no lo son! 

Pero justo había unas expectativas que estaban cargadas como dos strings vacíos. Es decir, el problema era que las expectativas estaban vacías, no que no hubiera habido expectativas (trabalenguas!)
