### ISSUE TITLE
Allow mulang to generate signatures 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mulang#57]
It would be nice if mulang could support signatures generation. For example, given the following haskell code: 

```haskell
foo :: Int -> Int
foo x = x + 1
```

It should produce
 
* `[TypedSignature "foo" ["Int"] "Int"]`
* or even `foo :: Int -> Int`

And given the following Prolog code: 

```prolog
foo(X, X).
foo(X, Y) :- bar(Y).
```

It should produce
 
* `[UntypedSignature "foo" 2]`
* or even `foo/2`

**Comment by flbulgarelli** [comment]
@faloi

**Comment by faloi** [comment]
<3
