### ISSUE TITLE
Add  InheritsFrom inspection

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mulang#83]
Add support for `InheritsFrom` inspection - e.g.: 

* `Reactor` `Not:InheritsFrom:List`: _class `Reactor` must not inherit from `List`_
* `InheritsFrom:List`: _there must be a class that inherits from from `List`_
* `InheritsFrom:^Person`: _there must be a class that is not  a `Person`_

Also we could add `UsesInheritance`, to check that a class declaration indicates superclass.

**Comment by flbulgarelli** [comment]
@aguspina please check if this is what you want?

**Comment by aguspina** [comment]
Yes this should work... I was looking for smth like `Reactor` `Not:InheritsFrom:*`, but the last approach you suggest seems ok -> `Reactor` `Not:UsesInheritance`

**Comment by faloi** [comment]
The second one seems semantically better, since `Reactor` would probably inherit from something like `Object`; and you want to check whether the student wrote something like `extends Pirulo`.
